{
  if (closeable != null) {
    try {
      closeable.close();
    }
 catch (    Exception e) {
      log.error("Error during close: ",e);
    }
  }
}
